spring:
  application:
    name: ai-text-tools-backend

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

management:
  endpoint:
    loggers:
      access: unrestricted
  endpoints:
    web:
      exposure:
       include: loggers

gemini:
  api:
    key: ${GEMINI_API_KEY}
